export const topCities = ['New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'San Francisco',
  'Columbus',
  'Indianapolis',
  'Fort Worth',
  'Charlotte',
  'Seattle',
  'Denver',
  'St. Louis',
  'Washington',
  'Boston',
  'Detroit',
  'Nashville',
  'Memphis',
  'Portland',
  'Oklahoma City',
  'Las Vegas',
  'Louisville',
  'Baltimore']
